### ISSUE TITLE
Customize/improve README

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-hubot-halpy#1]
This repos docs need to be up to snuff with the rest ;)

**Comment by patcon** [comment]
https://edgi.slack.com/archives/C55Q9LDJR/p1493361803352705

**Comment by dcwalk** [comment]
I'm closing this as done based on this commit: https://github.com/edgi-govdata-archiving/edgi-hubot-halpy/commit/0fd2a3ef6492a0886bf9a81665375e5288b6abbe, I think we should reticket specific improvements now that we generally have a descriptive readme :)

Thanks @patcon 👻
