### ISSUE TITLE
Announce upcoming zoom meetings in chat

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-hubot-halpy#10]
Reticketed from #9

@dcwalk for recurring meetings, would it be helpful to auto-drop the meeting link in chat, so that it doesn't rely on someone doing that? We could make it channel-specific, but might also be interesting to have it be global, and then it might:
* make it more widely known when folks are meeting, and about what
* make it feel more welcoming to drop in
* make it more likely to cross-pollinate our video calls, probably the most intimate and "high-bandwidth" spaces we have available outside in-person meetings :)

**Comment by dcwalk** [comment]
This is 👍  from me. Reminders posted to #general and maybe a specified channel would be amazing?
Is there a way to have that determined based on text in the description field of a google event? (and have like the zoom link as the "location"?

**Comment by patcon** [comment]
Oh you're right! It might be more versatile to read from calendar instead of zoom... and then someone could schedule with other services too, and it wouldn't break or fragment the functionality.

Although I feel the zoom command might also need to mess with the calendar in this case. Seems it would break the chain of convenience if someone said `halpy zoom me 6pm Website Meeting` but then it didn't auto-drop a reminder in chat when it was starting. (but maybe i'm being precious :) )
