### ISSUE TITLE
Chatbot command for adding #coverage news items to airtables

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-hubot-halpy#15]
## Current Behavior

Someone (often @lourdesvera) must do the task of adding press releases to airtable. Due to the nature of the task, it is done by a single person for indefinite periods of time. It is invisible work. Others don't often think to help.

## Desired Behavior

If new press entries could be added to the press coverage table via a public slack command, then it could be more of a public, shared task.

With just the link, we could add the title and publish date, and some other simple details. The remaining details could be filled in manually every so often, when someone visits the airtable on a less regular basis.

## Proposal

Add a halpy chatbot command that works like this:

    myname> halpy add press https://example.com/article.html
    halpy> added the following article to the press database: "Some headline" (Mar 12, 2018) by Jane Doe
    myname> halpy add press https://example.com/article.html
    halpy> the link you submitted is already in the press database

------

It would be nice if anyone could add items to the press coverage table from the slack team, so it's not all on one person to maintain it. We can do this with a chatbot command.

* `edgi` namespace is prob nice, so our custom commands are a little more clear.
* [coverage table on airtable](https://airtable.com/tbly4BdiQCqltcXFQ/viwImhd5RltuVIndT) [private]
* [airtable api method for creating item](https://airtable.com/apps6l3sgNsC4WzOq/api/docs#curl/table:coverage:create) [private]
* [`airtable.js` node library](https://github.com/airtable/airtable.js)

This is probably the command format we'd want

```
@halpy edgi coverage add 05/27/2017 http://example.com
```

This is an api call that check whether the link already exists in the table:

```
http GET "https://api.airtable.com/v0/apps6l3sgNsC4WzOq/Coverage?maxRecords=3&view=Main%20View" Authorization:"Bearer $AIRTABLE_API_KEY" filterByFormula=="SEARCH('https://thetech.com/2017/02/22/datarescue-students-collaborate-vital', {Link}) > 0" maxRecords==200
```

**Comment by dcwalk** [comment]
Could to speak a little bit to how adding something to the airtable would add details about what is covered at that URL? 

And does that mean that the airtable coverage would somehow be checking against all coverage? (Which is the difficulty that I think that repo is addressing: reconciling across updating sources)

**Comment by patcon** [comment]
https://github.com/mozilla/readability
