### ISSUE TITLE
Chatbot command to auto-invite new user to GitHub orgs

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-hubot-halpy#16]
blocked on https://github.com/edgi-govdata-archiving/edgi-hubot/issues/17

There are some niche things where new users are roadblocked on until they become elevated members of some sort
- Unable to use team mentions like `@edgi-govdata-archiving/lieutenants`
- unable to self-assign issues without help

Both of these would be helpful for smooth self-directed onboarding, using [our new experimental Trello method](https://trello.com/c/A04j5OpU/6-start-your-first-github-issue)

A user can become what I've called an "elevated member" in two ways:
- being added to a team with read access on a repo (even when repo already public)
- being added to an org as a member (only a good idea if org settings dictate general members get read-only, not write access)

I suggest we create a halpy command to allow people to add themselves to the team from slack.

```
jane-on-slack: @halpy team me @jane-on-github
halpy: @jane: Done and done! You've been added to the following GitHub teams:
       https://github.com/edgi-govdata-archiving
       https://github.com/archivers-space
halpy: Accept your invitations by visiting the above links!
       If you'd like your membership publicized on your profile, don't forget to visit
       the "People" tab on each, and set your membership to "Public" :)
```

cc: @b5

**Comment by Mr0grog** [comment]
Can we make Hubot auto-DM new Slack members? Commands like these seem kind of arcane and hard to discover, which is especially problematic when their function is so essential.

**Comment by patcon** [comment]
Good point. Thanks a bunch for saying so, man

The one thing I would say, is that I personally see a core function of this chat automation (chatops) thing as a merger of social and automation. One of the biggest reasons i am excited to automate is to re-merge the "doing" and "teaching" of tasks, which were severed when moving from physical offices to remote chat spaces. The doing now most often happens out-of-band of the shared social chat channel, to the institutional detriment imho :)

So I worry we lose much of the value if we opt for magic one-time auto-DM'd private messages, rather than arcane [for now?] chat commands in shared channels. I'm not sure if I'm expressing myself fully here, but I hope it makes sense.

Any thoughts on the above? In light of it, would you still lean toward auto-DMs?

**Comment by patcon** [comment]
Also, re "arcane". The idea would be to introduce new people early on to the idea of interacting with the chatbot for important tasks, so we'd add a checklist item to [this onboarding trello card](https://trello.com/c/yRMYHQie/13-get-memberized-on-our-github-teams):

- [ ] Run this chatbot command in Slack: `@halpy team me @<github-username>`

**Comment by Mr0grog** [comment]
I guess I would say that my universal experience with chatbots is that:

- They are confusing when you first encounter them unless you’ve been pre-informed
- If you’re just told to “run this command” and you aren’t already familiar with chatbots, that is seems confusing and weird
- Once you learn about bots or run _a_ command, the immediate next question is “what else does it do/how do I use it,” to which the answer is usually “go look at the repo,” which is a big time-sink if you are capable of understanding the code and a magical black box if you aren’t a programmer or familiar with the particular tool/language/whatever
- For commands that actually do important workflow things (as opposed to, say, adding a gif in the chat), it’s unclear the protocol and procedure around them

All that is to say, chatbots are cool and helpful and can keep some work “in-band,” as you noted, but for a lot of people, especially in a large public project with a variety of technical and non-technical contributors, they can be *really* confusing and *need* some explicit explanation and contextualizing.

**Comment by patcon** [comment]
Ok, that was a really great explanation. You're totally right -- this needs some proper and full attention.

Would it be a step in the right direction if this domain, "interacting with chatbots", were to get it's own explicit trello "card(s)" in the onboarding?

Things like:
- Send a private message to the bot, to see all commands: `/msg @halpy help`
- Run a test command in a sandbox channel. `@halpy do a thing`

And aside from my feeble first-past idea above (!), might you have any suggestions on how we could otherwise bring that "explicit explanation and contextualizing"?

(Thanks again for the comments Rob!)

**Comment by Mr0grog** [comment]
Augh, totally thought I replied to this 😓

Those sound great. If it makes sense for a command to have a deeper description, maybe also `@halpy help [command]` or `@halpy tell me about [command]` or `@halpy describe [command]`.

**Comment by dcwalk** [comment]
Filling time at the airport 🛩 , so gonna chime in: I agree that in my experience chatbots can be largely neglected, taken up by 1 or 2 power users, or just confusing.

Excited for the potential for in-band aids, but I also think adding some cue to the welcome message, in addition to the onboarding to Web Monitoring workflow would be helpful :)

Also, patcon, probably out of the loop, my sense is the audience to the Trello onboarding is volunteer contributors (Archivers) and not EDGI. If so I think understanding what non-Trello completers will need is important
