### ISSUE TITLE
Add NLP to our custom commands

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/edgi-hubot-halpy#23]
NLP = natural language processing

Might make our custom commands a little more forgiving.
https://github.com/ibm-cloud-solutions/hubot-ibmcloud-nlc

@janakrajchadha mentioned that he had some experience working on NLP chatbot systems in previous work, so :tada: 

Probably low priority, but patches always welcome!

**Comment by janakrajchadha** [comment]
Thanks for opening this @patcon! I would love patches from others coming in. 
For those who want to know more 
- [https://www.datascience.com/blog/introduction-to-natural-language-processing-lexical-units-learn-data-science-tutorials](url)
- [https://blog.algorithmia.com/introduction-natural-language-processing-nlp/](url)

For those who want to try something out
- [https://spacy.io/](url)
- [https://nlp.stanford.edu/](url)
