### ISSUE TITLE
Update Hubot to 3.1.1

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/edgi-hubot-halpy#34]
There’s a new version out with some important fixes, so we should update Hubot to v3.1.1.

See also Slack discussion: https://edgi.slack.com/archives/C57QL8M1T/p1532479143000029

**Comment by patcon** [comment]
Fixed the vuln warning that i think instigated this: https://github.com/edgi-govdata-archiving/edgi-hubot-halpy/compare/0fd2a3ef6492a0886bf9a81665375e5288b6abbe...29a59e9eb6574de12d81bf64cdc45cc9bbf76a90

If the bump to v3 is important for other reasons, def don't hesitate to re-open :)
