### ISSUE TITLE
Consider shutting down Halpy and archiving this repo

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/edgi-hubot-halpy#46]
On Slack (https://edgi.slack.com/archives/C57QL8M1T/p1554405109010200), I asked whether we’re actually using Halpy that much and what for, wondering whether there might be a way to pare it down to be more maintainable or switch to other tools—this repo is getting behind in its dependencies and has security vulnerabilities (which matter a lot since we give it access to things we pay for).

Folks said we make active use of it for:

1. Displaying Google Alerts in the #coverage channel. Slack now has a built-in tool for something like this using the `/feed` command, though I’m not sure whether it’s effectively the same or not.

2. Creating impromptu Zoom meetings.

It felt like the overriding view was that this might not be worth maintaining, so we should consider shutting it down and archiving this repo. Any thoughts or concerns?

/cc @titaniumbones @lightandluck @Frijol @patcon

**Comment by lightandluck** [comment]
Apologies to Pat, Matt, and everyone else who put time into this, but I'd vote to remove Halpy from Slack.

The Google Alerts have mostly been picking up weird stories like stock prices changes so tends to clutter the #coverage channel and I don't think people use it to create impromptu zoom meetings either. We're meeting overloaded, so people stick to recurring meetings or schedule meetings ahead of time in Zoom itself. I don't see any value in what Halpy is doing now.

I know there's hope that Halpy could help with onboarding new people to Slack, but we haven't had the capacity to further that or maintain this. If we wanted to leave this open as a possible project for any new volunteers or someone who wanted to own it, would it make sense to leave the repo unarchived? Or unarchive it if that happens?

**Comment by titaniumbones** [comment]
> We're meeting overloaded, so people stick to recurring meetings or schedule meetings ahead of time in Zoom itself. I don't see any value in what Halpy is doing now.

Completely agree -- let's kill it!

I think we may as well archive the project -- both hubot & the slack API are moving targets and we would probably start nearly from scratch if we ever wanted to reinvent this tool (which seems unlikely to me right now).

**Comment by Mr0grog** [comment]
Same for [halpy-ng](https://github.com/edgi-govdata-archiving/halpy-ng)?

**Comment by titaniumbones** [comment]
Yes!

On May 3, 2019 12:37 p.m., Rob Brackett <notifications@github.com> wrote:

Same for halpy-ng<https://github.com/edgi-govdata-archiving/halpy-ng>?

**Comment by patcon** [comment]
I def support archiving if people aren't getting any use out of it! Thanks for asking <3

No opinions on archiving vs not. Seems nice to have low-hanging fruit for new folks, but not sure this best serves that need... :)

**Comment by Mr0grog** [comment]
Alright, we can start by turning off the Heroku dynos, so it’s easy to spin back up if someone not on this issue or the Slack discussion discovers they are relying on it.

**Comment by Mr0grog** [comment]
OK, I turned off Halpy by disabling the web dyno and changing all the scheduler jobs to:

```sh
echo 'DEPRECATED: <original scheduler script>'`
```

If no issues in a week, we’ll revisit whether to archive the repo?

**Comment by lightandluck** [comment]
Thanks, Rob 🚀 
+1 to archiving in a week

**Comment by Mr0grog** [comment]
OK, I updated the README in #47. If people are happy with that, I think we should archive this repo after merging that. Archiving makes the status extra clear and also turns off automated things like security notices (which I at least would appreciate).

@titaniumbones is there a Heroku project (or some other deployment) we need to turn off before doing the same for halpy-ng?

**Comment by Mr0grog** [comment]
Alright, I’m going to go ahead and close this and archive the repo.
